// src/app/resume/resume.component.ts
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import { RouterOutlet, RouterLink } from "@angular/router";
import { NavbarComponent } from "../components/navbar/navbar.component";

@Component({
    selector: 'resume',
    standalone: true,
    imports: [CommonModule, RouterOutlet, RouterLink, NavbarComponent],
    templateUrl: './resume.component.html',
    styleUrls: ['./resume.component.scss']
    
  })
  export class ResumeComponent {
    title = 'resume';
  }
  
<div class="resume-page">
    <div class="resume-container">
        <header class="resume-header">
            <h1>My Resume</h1>
            <p class="resume-subtitle">Contact Info and Links</p>
            <div class="contact-links">
                <a class="contact-chip">
                    <img src="../../assets/resume/email_icon.png" alt="Email" />
                    <span>patrick[at]smathers.dev</span>
                </a>
                <a href="https://www.linkedin.com/in/patrick-smathers/" class="contact-chip">
                    <img src="../../assets/resume/LI-In-Bug.png" alt="LinkedIn" />
                    <span>patrick-smathers</span>
                </a>
                <a href="https://github.com/smathep/" class="contact-chip">
                    <img src="../../assets/resume/GitHub-Mark-Light-120px-plus.png" alt="GitHub" />
                    <span>smathep</span>
                </a>
            </div>
            <p class="download-link"><a id="links" href="../../assets/resume/Resume - Patrick Smathers.pdf">Download PDF version</a></p>
        </header>

        <section class="resume-section">
            <h2>Education</h2>
            <div class="resume-card">
                <div class="experience-header">
                    <div>
                        <h3>Clemson University <img src="../../assets/resume/Paw_RGB__Orange.png" width="30px" style="vertical-align: middle" /></h3>
                        <p class="role">B.S. in Computer Science — GPA 3.80</p>
                    </div>
                    <div class="experience-meta">
                        <span class="location">Clemson, SC</span>
                        <span class="date">May 2023</span>
                    </div>
                </div>
            </div>
        </section>

        <section class="resume-section">
            <h2>Work Experience</h2>

            <div class="resume-card">
                <div class="experience-header">
                    <div>
                        <h3>Microsoft</h3>
                        <p class="role">Software Engineer</p>
                    </div>
                    <div class="experience-meta">
                        <span class="date">June 2025 — Present</span>
                    </div>
                </div>
            </div>

            <div class="resume-card">
                <div class="experience-header">
                    <div>
                        <h3>LPL Financial</h3>
                        <p class="role">Engineer I, Software Development</p>
                    </div>
                    <div class="experience-meta">
                        <span class="date">June 2023 — May 2025</span>
                    </div>
                </div>
                <ul>
                    <li>Designed, implemented, and maintained C# APIs and Angular UIs for eSignature applications used by tens of thousands of advisors and staff.</li>
                    <li>Implemented new system to manage and bundle multiple eSignature requests into one eSignature signing ceremony.</li>
                    <li>Assisted with migrating eSignature UI, API, and Databases to AWS. Led a migration from on-prem SQL Server to PostgreSQL on AWS RDS.</li>
                </ul>
            </div>

            <div class="resume-card">
                <div class="experience-header">
                    <div>
                        <h3>LPL Financial</h3>
                        <p class="role">Technology Intern — Software Development</p>
                    </div>
                    <div class="experience-meta">
                        <span class="date">June 2022 — August 2022</span>
                    </div>
                </div>
                <ul>
                    <li>Worked on a team maintaining and improving a system for financial investors to view accounts and contributions.</li>
                    <li>Created and contributed to APIs in C# to enable investors to better manage their money.</li>
                </ul>
            </div>

            <div class="resume-card">
                <div class="experience-header">
                    <div>
                        <h3>Clemson University — School of Computing <img src="../../assets/resume/Paw_RGB__Orange.png" width="30px" style="vertical-align: middle" /></h3>
                        <p class="role">Mobile App Developer — Full Stack</p>
                    </div>
                    <div class="experience-meta">
                        <span class="date">Jan 2023 — May 2023</span>
                    </div>
                </div>
                <ul>
                    <li>Worked with Clemson's Cooperative Extension and College of Agriculture, Forestry, and Life Sciences to develop iOS and Android apps for their WalkSC Program.</li>
                    <li>Built an app in React Native that has feature parity across platforms.</li>
                    <li>Setup and maintained cloud infrastructure on AWS to run an API and Database, and manage DNS records.</li>
                    <li>Created detailed technical documentation on how to setup the backend infrastructure from scratch and detailed app processes for future developers.</li>
                </ul>
            </div>

            <div class="resume-card">
                <div class="experience-header">
                    <div>
                        <h3>Clemson University — School of Computing <img src="../../assets/resume/Paw_RGB__Orange.png" width="30px" style="vertical-align: middle" /></h3>
                        <p class="role">Lead Teaching Assistant</p>
                    </div>
                    <div class="experience-meta">
                        <span class="date">Jan 2022 — May 2022</span>
                    </div>
                </div>
                <ul>
                    <li>Created and scheduled the in-person office hours rooms.</li>
                    <li>Assisted in presenting and developing new training content for new UTAs to teach important basics.</li>
                    <li>Interviewed potential new UTAs and assisted in assigning UTAs to classes.</li>
                </ul>
            </div>

            <div class="resume-card">
                <div class="experience-header">
                    <div>
                        <h3>Clemson University — School of Computing <img src="../../assets/resume/Paw_RGB__Orange.png" width="30px" style="vertical-align: middle" /></h3>
                        <p class="role">Teaching Assistant</p>
                    </div>
                    <div class="experience-meta">
                        <span class="date">Aug 2021 — Dec 2021</span>
                    </div>
                </div>
                <ul>
                    <li>Co-led an introductory CS lab class alongside another TA.</li>
                    <li>Graded assignments and labs to help provide timely feedback on submitted work.</li>
                    <li>Partially automated project testing to speedup unpacking files, compiling, and running tester classes.</li>
                    <li>Worked alongside a team of UTAs to provide support to students outside of lab and lecture during office hours.</li>
                </ul>
            </div>

            <div class="resume-card">
                <div class="experience-header">
                    <div>
                        <h3>Clemson University — CCIT <img src="../../assets/resume/Paw_RGB__Orange.png" width="30px" style="vertical-align: middle" /></h3>
                        <p class="role">Laptop Support Technician</p>
                    </div>
                    <div class="experience-meta">
                        <span class="date">Jan 2021 — Dec 2021</span>
                    </div>
                </div>
                <ul>
                    <li>Provided support to students, faculty, and staff regarding laptop software issues and diagnosing hardware issues.</li>
                    <li>Trained new student workers in protocols and procedures.</li>
                </ul>
            </div>
        </section>

        <section class="resume-section">
            <h2>Skills</h2>
            <div class="resume-card">
                <div class="skills-grid">
                    <div class="skill-category">
                        <h4>Proficient</h4>
                        <div class="skill-tags">
                            <span class="skill-tag">Java</span>
                            <span class="skill-tag">C++</span>
                            <span class="skill-tag">C#</span>
                            <span class="skill-tag">Angular</span>
                            <span class="skill-tag">macOS</span>
                            <span class="skill-tag">Windows</span>
                        </div>
                    </div>
                    <div class="skill-category">
                        <h4>Experienced</h4>
                        <div class="skill-tags">
                            <span class="skill-tag secondary">C</span>
                            <span class="skill-tag secondary">Python</span>
                            <span class="skill-tag secondary">HTML/CSS</span>
                            <span class="skill-tag secondary">SQL</span>
                            <span class="skill-tag secondary">Shell Scripting</span>
                            <span class="skill-tag secondary">AWS</span>
                            <span class="skill-tag secondary">Agile</span>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="resume-section">
            <h2>Projects</h2>
            <div class="resume-card">
                <p>Check out the <a id="links" routerLink="/projects">Projects page</a> for more detail!</p>
                <ul>
                    <li><a id="links" href="https://github.com/ClemBotProject/ClemBot">ClemBot</a> — Contributed to a large discord bot written in Python and C# with a PostgreSQL DB</li>
                    <li><a id="links" href="https://github.com/smathep/Mandelbrot">Mandelbrot</a> — Java program that renders the Mandelbrot set with multithreading support</li>
                    <li><a id="links" href="https://github.com/smathep/GameOfLife">Conway's Game of Life</a> — Interactive Life simulation in Java</li>
                    <li><a id="links" href="http://fractals.iapetus11.me">Fractals.tech</a> — Hackathon project for creating and downloading fractal images</li>
                </ul>
            </div>
        </section>

        <section class="resume-section">
            <h2>Awards & Recognitions</h2>
            <div class="resume-card">
                <ul>
                    <li>Palmetto Fellows and STEM Enhancement (August 2020 — Spring 2023)</li>
                    <li>President's List — Fall 2020; Fall 2021; Spring 2022</li>
                    <li>Dean's List — Spring 2021; Fall 2022; Spring 2023</li>
                    <li>CUHackit Hackathon Award — Best Use of a .tech Domain (<a id="links" href="http://fractals.iapetus11.me">fractals.tech</a>)</li>
                    <li>Inducted into Upsilon Pi Epsilon — International CS Honors Society — Spring 2022</li>
                    <li><abbr title="Hispanic Scholarship Fund">HSF</abbr> Scholar: 2021; 2022</li>
                    <li>1 of 100 HSF STEM Summit Invitees — 2022</li>
                </ul>
            </div>
        </section>

        <section class="resume-section">
            <h2>Activities & Interests</h2>
            <div class="resume-card two-col">
                <div>
                    <h4>Activities</h4>
                    <ul>
                        <li>Clemson Photography Club: Spring 2021 — Spring 2022</li>
                    </ul>
                </div>
                <div>
                    <h4>Interests</h4>
                    <ul class="interests-list">
                        <li>Photography</li>
                        <li>Programming</li>
                        <li>Technology</li>
                        <li>Video Games</li>
                        <li>Music</li>
                        <li>Science</li>
                    </ul>
                </div>
            </div>
        </section>
    </div>
</div>

// src/pages/Resume.jsx
import React from 'react';
// import ReactDOM from 'react-dom/client';
// import 'bootstrap/dist/css/bootstrap.min.css';
// import './index.css';
// import App from '../App';
// import Navbar from '../Navbar';
// import reportWebVitals from '../reportWebVitals';

export default function Resume(){
    return (
        <div>
          <div id="content" >
            
            {/* <br/> */}
            <br/>
            <h1>My Resume</h1>
            <h2>Contact Info and Links</h2>
            
            <div class="table" className='centered'>
                <ul id="horizontal-list">
                    <li><img src="./assets/resume/email_icon.png" width="60px" style={{"vertical-align": "middle", "margin-right": "3px"}}/> <a id="links" href="mailto:patrick@patricksmathers.com">patrick@patricksmathers.com</a></li>
                    <li><img src="./assets/resume/LI-In-Bug.png" width="50px" style={{"vertical-align": "middle", "margin-right": "1px"}}/> <a id="links" href="https://www.linkedin.com/in/patrick-smathers/">patrick-smathers</a></li>
                    <li><img src="./assets/resume/GitHub-Mark-Light-120px-plus.png" width="50px" style={{"vertical-align": "middle", "margin-right": "1px"}}/> <a id="links" href="https://github.com/smathep/">smathep</a></li>
                </ul>
            </div>
            <p className='centered'><a id="links" href="./assets/resume/Resume - Patrick Smathers.pdf">For a downloadable version, click here!</a></p>
            
            <br/>
            <h2>Education <img src="./assets/resume/Paw_RGB__Orange.png" width="50px" style={{"vertical-align": "middle", "padding-bottom": "2px"}}/></h2>  
            
            <p style={{"float": "left"}}>
                Clemson University<br/>
                B.S. in Computer Science - GPA 3.80
            </p>
            <p style={{"float": "right"}}> 
                Clemson, SC <br></br>
                May 2023
            </p>
            
            <br/>
            <br/>
            <br/>
            <h2>Work Experience</h2>
            <br/>
            <h3>LPL Financial</h3>
            <p>
                Engineer I, Software Development (June 2023 - Present)
            </p>
            <p>
                Technology Intern - Software Devlopment (June 2022 - August 2022)
                <br />
                <ul>
                    <li>Worked on a team maintaining and improving a system for financial investors to view accounts and contributions.</li>
                    <li>Created and contributed to APIs in C# to enable investors to better manage their money.</li>
                </ul>
            </p>
            <br />
            
            <h3 >Clemson University - School of Computing <img src="./assets/resume/Paw_RGB__Orange.png" width="50px" style={{"vertical-align": "middle"}}/> </h3>
            <p>
                Mobile App Developer - Full Stack (January 2023 - May 2023)
                <br />
                <ul>
                    <li>Worked with Clemson's Cooperative Extension and College of Agriculture, Forestry, and Life Sciences to develop iOS and Android apps for their WalkSC Program.</li>
                    <li>Built an app in React Native that has feature parity across platforms.</li>
                    <li>Setup and maintained cloud infrastructure on AWS to run an API and Database, and manage DNS records.</li>
                    <li>Created detailed technical documentation on how to setup the backend infrastructure from scratch and detailed app processes for future developers.</li>
                </ul>
            </p>
            <p>
                Lead Teaching Assistant (January 2022 - May 2022)
                <br />
                <ul>
                    <li>Created and scheduled the in-person office hours rooms.</li>
                    <li>Assisting in presenting and developing new training content for new UTA's to teach important basics.</li>
                    <li>Interviewed potential new UTAs and assisted in assigning UTAs to classes.</li>
                </ul>
            </p>
            <p>
                Teaching Assistant (August 2021 - December 2021)
                <ul>
                    <li>Co-led an introductory CS lab class alongside another TA.</li>
                    <li>Graded assignments and labs to help provide timely feedback on submitted work.</li>
                    <li>Partially automated project testing to speedup unpacking files, compiling, and running tester classes.</li>
                    <li>Worked alongside a team of UTAs to provide support to students outside of lab and lecture during office hours.</li>
                </ul>
            </p>
            <br />
            <h3>Clemson University - Clemson Computing and Information Technology <img src="./assets/resume/Paw_RGB__Orange.png" width="50px" style={{"vertical-align": "middle;"}}/> </h3>
            <p>
                Laptop Support Technician (January 2021 - December 2021)
                <ul>
                    <li>Provided support to students, faculty, and staff regarding laptop software issues and diagnosing hardware issues</li>
                    <li>Trained new student workers in our protocols and procedures</li>
                </ul>
            </p>
            <br />
            <h2>Skills</h2>
            <ul>
                <li>
                    Experience with Java (Oracle Certified Associate in Java 7), C++, MacOS, Windows
                </li>
                <li>
                    Exposure to C, Python, HTML/CSS, MySQL, shell scripting, AWS (Route 53, CloudFront, Lambda, S3), Agile Dev., C# 
                </li>
            </ul>
            <br />
            <h2>Projects</h2>
            <p>Check out the Projects page for more detail!</p>
            <ul>
                <li><a id="links" href="https://github.com/ClemBotProject/ClemBot">ClemBot</a> - Contributed to a large discord bot, named ClemBot, written in Python and C# and integrating a PostgresSQL DB</li>
                <li><a id="links" href="https://github.com/smathep/Mandelbrot">Mandelbrot</a> - Java program that can render the Mandelbrot set in different resolutions, locations, zoom factors, and utilizing a variable number of threads</li>
                <li><a id="links" href="https://github.com/smathep/GameOfLife">Conway's Game of Life</a> - Created a Life simulation based on Conway's Life in Java that allows user interaction and manipulation</li>
                <li><a id="links" href="http://fractals.iapetus11.me">Fractals.tech</a> - Group hackathon project where users can create different types of fractals on a website, modify their parameters and appearance, and download the image. Won a category award for using a .tech domain. </li> 
            </ul>
            
            <br />
            <h2>Awards/Recognitions</h2>
            <ul>
                <li>Palmetto Fellows and STEM enhancement (August 2020 - Spring 2023)</li>
                <li>President's List - Fall 2020; Fall 2021; Spring 2022</li>
                <li>Dean's List - Spring 2021; Fall 2022; Spring 2023</li>
                <li>CUHackit Hackathon Award (Team Project) - Best Use of a .tech Domain (<a id="links" href="http://fractals.iapetus11.me">https://fractals.tech</a> - Has been updated and maintined by my friend on his website!)</li>
                <li>Inducted into to Upsilon Pi Epsilon - International Computer Science Honors Society - Spring 2022</li>
                <li> <u><abbr title="Hispanic Scholarship Fund">HSF</abbr></u> Scholar Designation: 2021; 2022 </li>
                <li>1 of 100 HSF STEM Summit Invitees - 2022</li>
            </ul>
            
            <br />
            <h2>Activites</h2>
            <ul>
                <li>Clemson Photography Club: Spring 2021 - Spring 2022</li>
            </ul>
            
            <br />
            <h2>Interests</h2>
            <ul>
                <li>Photography</li>
                <li>Programming</li>
                <li>Technology</li>
                <li>Video Games</li>
                <li>Music</li>
                <li>Science</li>
                
            </ul>
          </div>
        </div>
    )
}
// const root = ReactDOM.createRoot(document.getElementById('root'));
// root.render(
//   <React.StrictMode>
//     <App />
//   </React.StrictMode>,
//   document.getElementById('root')
// );

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
// reportWebVitals();
 
// export default Resume
